# Generated by Django 6.0 on 2026-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_optimizationsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationsuggestion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Decision'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Acceptance status', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='preferred_theme',
            field=models.CharField(default='Executive', help_text='Visual theme style', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Parsed resume elements', null=True),
        ),
    ]
